on: 
  push:
    branches: 
      - 'development'
name: OCI-Marketplace
jobs:
  test-terraform-code: 
    name: tf-job-name
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install-go
      run: |
        echo "This is supposed to run go installation"
        sh devops/prepare-job.sh
    - name: run-terratest
      env:
        TF_ACTION_WORKING_DIR: ./terraform
        TF_VAR_compartment_ocid: ${{ secrets.TF_VAR_compartment_ocid }}
        TF_VAR_fingerprint: ${{ secrets.TF_VAR_fingerprint }}
        TF_VAR_private_key: ${{ secrets.TF_VAR_private_key }}
        TF_VAR_tenancy_ocid: ${{ secrets.TF_VAR_tenancy_ocid }}
        TF_VAR_user_ocid: ${{ secrets.TF_VAR_user_ocid }}
      run: |
        mv devops/terraform-h2o-quickstart_test.go $HOME/go/src/terratest/test
        cd $HOME/go/src/terratest/test
        dep ensure
        go test -v terraform-h2o-quickstart_test.go
        create-mp-image:
    name: create-image
    runs-on: ubuntu-latest
    needs: test-terraform-code
    steps:
    - name: packer-create-image
      run: |
        echo "This will create a image if first job output is Pass"
    