on: 
  push:
    branches: 
      - 'development'
name: OCI-Marketplace
jobs:
  test-terraform-code: 
    name: test-terraform-code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install-dependencies
      run: |
        sh devops/prepare-job.sh
        #mv devops/terraform-h2o-quickstart_test.go $HOME/go/src/terratest/test
        #cd $HOME/go/src/terratest/test
        #dep ensure
    - name: run-terratest
      working-directory: terraform
      env:
        TF_VAR_compartment_ocid: ${{ secrets.TF_VAR_compartment_ocid }}
        TF_VAR_fingerprint: ${{ secrets.TF_VAR_fingerprint }}
        TF_VAR_private_key: ${{ secrets.TF_VAR_private_key }}
        TF_VAR_tenancy_ocid: ${{ secrets.TF_VAR_tenancy_ocid }}
        TF_VAR_user_ocid: ${{ secrets.TF_VAR_user_ocid }}
      run: |
        export TF_ACTION_WORKING_DIR=$PWD
        terraform 0.12upgrade -yes
        #go test -v $HOME/go/src/terratest/test/terraform-h2o-quickstart_test.go
  create-mp-image:
    if: success()
    name: packer-create-image
    runs-on: ubuntu-latest
    needs: test-terraform-code
    steps:
    - name: packer-create-image
      run: |
        echo "Use Packer to create OCI image with cleanup-script and partner bits (from scripts dir in repo)"
        packer build devops/marketplace-image.json
  submit-image-listing:
    if: success()
    name: submit-image
    runs-on: ubuntu-latest
    needs: create-mp-image
    steps:
    - name: submit-image-publisher-portal
      run: |
        echo "This will submit the image to Publisher Portal"
    