on: 
  push:
    branches: 
      - 'development'
name: OCI-Marketplace
jobs:
  test-terraform-code: 
    name: test-terraform-code
    runs-on: ubuntu-latest
    env:
      TF_VAR_compartment_ocid: ${{ secrets.TF_VAR_compartment_ocid }}
      TF_VAR_fingerprint: ${{ secrets.TF_VAR_fingerprint }}
      TF_VAR_private_key: ${{ secrets.TF_VAR_private_key }}
      TF_VAR_private_key_path: /home/runner/oci.pem
      TF_VAR_tenancy_ocid: ${{ secrets.TF_VAR_tenancy_ocid }}
      TF_VAR_user_ocid: ${{ secrets.TF_VAR_user_ocid }}
    steps:
    - uses: actions/checkout@master
    - name: install-dependencies
      run: |
        sh devops/prepare-job.sh
    - name: test-terraform-code
      working-directory: terraform
      run: |
        export TF_ACTION_WORKING_DIR=$PWD
        terraform init && terraform 0.12upgrade -yes
        echo "${{ secrets.TF_VAR_private_key }}" > /home/runner/oci.pem
        #go test -v $HOME/go/src/terratest/test/terraform-h2o-quickstart_test.go -timeout 20m
    - name: zip-and-upload-stack
      run: |
        zip -r $GITHUB_REPOSITORY.zip ../terraform/
      uses: actions/upload-artifact@master
      with:
        name: stack-archive
        path: ./$GITHUB_REPOSITORY.zip
    - name: create-marketplace-image
      if: success()
      #uses: actions/upload-artifact@v1
      run: |
        echo "Use Packer to create OCI image with cleanup-script"
        packer version
        #packer build /home/runner/packer-template.json
  submit-image-listing:
    if: success()
    name: submit-image
    runs-on: ubuntu-latest
    needs: test-terraform-code
    steps:
    - name: submit-image-to-publisher-portal
      run: |
        echo "This will submit the image to Publisher Portal"
    